(* SPDX-FileCopyrightText: 2026 NetTopologySuite.Proofs contributors *)
(* SPDX-License-Identifier: BSD-3-Clause *)

(* ============================================================================
   NetTopologySuite.Proofs.CompoundCurveKoc
   Vendored into clothoid-halley-coq/coq/ under BSD-3-Clause only
   (see coq/LICENSE_BSD-3-Clause.txt). Not licensed as EUPL-1.2.
   ----------------------------------------------------------------------------
   The analytic core of compound-curve railway alignment design, after

     W. Koc, "Design of compound curves adapted to the satellite
     measurements", The Archives of Transport 34(2), 2015, 37-49
     (doi:10.5604/08669546.1169211).

   THE REAL-WORLD PROBLEM.  Mobile GNSS surveys (antennas on a rail trailer,
   Poland's ASG-EUPOS network) deliver the as-built track axis as coordinates
   in the national grid ("system 2000", EPSG:2176-2180).  On degraded lines
   the track is often so deformed that the original design straights ("main
   directions") cannot be recovered, so re-alignment cannot use the classic
   symmetric pattern (transition - single arc - transition); the designer
   must connect the two surveyed directions with a COMPOUND CURVE (EN
   13803-1): two circular arcs of different radii R1, R2 joined by three
   transition curves TC1-TC3.  Koc's method writes the WHOLE system as
   closed-form equations in a local frame, so that alignment variants are
   generated by substituting design values (radii, transition lengths)
   instead of redrawing CAD geometry.  Every equation below is load-bearing
   in that pipeline -- and each has a concrete failure mode when implemented
   naively in floating point (frame drift between survey and design, a
   tangency center placed on the wrong side of the track producing a kink a
   train cannot run, a mis-set transition angle breaking the superelevation
   ramp at line speed).

   WHAT IS MECHANISED (paper eq |-> lemma):

     (1),(2) + (42),(43)  global<->local frame transform round-trips
                          (`koc_roundtrip_*`) and its isometry
                          (`koc_to_local_isometry`) -- survey points and
                          design geometry live in different frames; these
                          are the exactness conditions for moving between
                          them with zero information loss.
     Sec. 2 (clothoid)    linear curvature k(l) = l/(R L) integrates to the
                          tangent angle theta(l) = l^2/(2 R L)
                          (`koc_clothoid_angle_deriv`), with the end
                          conditions k(L) = 1/R and the type-independent
                          end angle theta(L) = L/(2R)
                          (`koc_clothoid_end_*`) that the whole tangency
                          bookkeeping of the paper rests on.
     (8),(9) / (23),(24)  the arc centre lies at distance R along the
                          normal of the tangency point
                          (`koc_center_on_normal`) -- stated sqrt-free by
                          carrying u > 0, u^2 = 1 + s^2.
     (31),(32)            the point of a circle where the tangent has a
                          prescribed slope (`koc_slope_point_on_circle`) --
                          where arc CA2 must end so that TC3 can land on
                          the second main direction.
     (11),(12) / (14),(15) setting out along a tangent: the point at
                          distance d along the slope-s direction
                          (`koc_tangent_setout`), and the surveyor's
                          tangent length d = R tan(alpha/2)
                          (`koc_tangent_length`).
     Worked example       an exact 3-4-5 instance (s = 3/4, u = 5/4,
                          R = 5): centre (3,-4) from K = (0,0), all checks
                          by rational arithmetic -- the corpus-style
                          concrete witness that the formulas are not
                          vacuous.

   All statements are sqrt-free (squared distances, normalisation carried
   as a hypothesis), matching the corpus convention that lets every proof
   close by `ring`/`field`/`nra` and keeps the axiom footprint at the
   standard classical-reals trio.

   No `Admitted`, no `Axiom`, no `Parameter`.

   Author: NetTopologySuite.Proofs contributors
   License: BSD-3-Clause (see coq/LICENSE_BSD-3-Clause.txt)
   AI assistance disclosure: AI-drafted, human-reviewed.
     Assisted-by: Claude
   ========================================================================== *)

Require Import Reals Lra Lia Ranalysis1.
Require Import Distance.
Local Open Scope R_scope.

(* -------------------------------------------------------------------------- *)
(* §1  Frame transforms: system 2000 <-> local coordinate system.             *)
(*                                                                            *)
(* Koc eqs (1),(2): survey point (Y,X) in the national grid maps to (x,y) in  *)
(* the local design frame with origin (Y0,X0) and rotation beta.  Eqs (42),   *)
(* (43) are the inverse used to send the chosen design variant back to the    *)
(* grid for setting out.                                                      *)
(*                                                                            *)
(* CONVENTION NOTE: the grid coordinates follow the papers' surveying (Y,X)   *)
(* ordering -- Y is the easting-like abscissa, X the northing-like ordinate   *)
(* of the Polish "system 2000" -- NOT the usual mathematical (X,Y).  The      *)
(* lemmas are order-agnostic (they never compare the two axes), but readers   *)
(* matching them against the papers should keep the (Y,X) order in mind.      *)
(* -------------------------------------------------------------------------- *)

Definition koc_local_x (Y0 X0 beta Y X : R) : R :=
  (Y - Y0) * cos beta + (X - X0) * sin beta.

Definition koc_local_y (Y0 X0 beta Y X : R) : R :=
  - (Y - Y0) * sin beta + (X - X0) * cos beta.

Definition koc_global_Y (Y0 X0 beta x y : R) : R :=
  Y0 + x * cos beta - y * sin beta.

Definition koc_global_X (Y0 X0 beta x y : R) : R :=
  X0 + x * sin beta + y * cos beta.

(* Round-trip grid -> local -> grid is the identity. *)
Theorem koc_roundtrip_global_local :
  forall Y0 X0 beta Y X,
    koc_global_Y Y0 X0 beta (koc_local_x Y0 X0 beta Y X)
                            (koc_local_y Y0 X0 beta Y X) = Y /\
    koc_global_X Y0 X0 beta (koc_local_x Y0 X0 beta Y X)
                            (koc_local_y Y0 X0 beta Y X) = X.
Proof.
  intros Y0 X0 beta Y X.
  unfold koc_global_Y, koc_global_X, koc_local_x, koc_local_y.
  pose proof (sin2_cos2 beta) as H. unfold Rsqr in H.
  split.
  - replace (Y0 + ((Y - Y0) * cos beta + (X - X0) * sin beta) * cos beta
             - (- (Y - Y0) * sin beta + (X - X0) * cos beta) * sin beta)
      with (Y0 + (Y - Y0) * (sin beta * sin beta + cos beta * cos beta))
      by ring.
    rewrite H. ring.
  - replace (X0 + ((Y - Y0) * cos beta + (X - X0) * sin beta) * sin beta
             + (- (Y - Y0) * sin beta + (X - X0) * cos beta) * cos beta)
      with (X0 + (X - X0) * (sin beta * sin beta + cos beta * cos beta))
      by ring.
    rewrite H. ring.
Qed.

(* Round-trip local -> grid -> local is the identity. *)
Theorem koc_roundtrip_local_global :
  forall Y0 X0 beta x y,
    koc_local_x Y0 X0 beta (koc_global_Y Y0 X0 beta x y)
                           (koc_global_X Y0 X0 beta x y) = x /\
    koc_local_y Y0 X0 beta (koc_global_Y Y0 X0 beta x y)
                           (koc_global_X Y0 X0 beta x y) = y.
Proof.
  intros Y0 X0 beta x y.
  unfold koc_global_Y, koc_global_X, koc_local_x, koc_local_y.
  pose proof (sin2_cos2 beta) as H. unfold Rsqr in H.
  split.
  - replace ((Y0 + x * cos beta - y * sin beta - Y0) * cos beta
             + (X0 + x * sin beta + y * cos beta - X0) * sin beta)
      with (x * (sin beta * sin beta + cos beta * cos beta)) by ring.
    rewrite H. ring.
  - replace (- (Y0 + x * cos beta - y * sin beta - Y0) * sin beta
             + (X0 + x * sin beta + y * cos beta - X0) * cos beta)
      with (y * (sin beta * sin beta + cos beta * cos beta)) by ring.
    rewrite H. ring.
Qed.

(* The transform is an isometry: squared distances are preserved, so
   chainage, gauge and clearance computations agree in both frames. *)
Theorem koc_to_local_isometry :
  forall Y0 X0 beta Y1 X1 Y2 X2,
    dist_sq (mkPoint (koc_local_x Y0 X0 beta Y1 X1)
                     (koc_local_y Y0 X0 beta Y1 X1))
            (mkPoint (koc_local_x Y0 X0 beta Y2 X2)
                     (koc_local_y Y0 X0 beta Y2 X2))
    = dist_sq (mkPoint Y1 X1) (mkPoint Y2 X2).
Proof.
  intros Y0 X0 beta Y1 X1 Y2 X2.
  unfold dist_sq, koc_local_x, koc_local_y; simpl.
  pose proof (sin2_cos2 beta) as H. unfold Rsqr in H.
  replace (((Y1 - Y0) * cos beta + (X1 - X0) * sin beta
            - ((Y2 - Y0) * cos beta + (X2 - X0) * sin beta))
           * ((Y1 - Y0) * cos beta + (X1 - X0) * sin beta
              - ((Y2 - Y0) * cos beta + (X2 - X0) * sin beta))
           + (- (Y1 - Y0) * sin beta + (X1 - X0) * cos beta
              - (- (Y2 - Y0) * sin beta + (X2 - X0) * cos beta))
             * (- (Y1 - Y0) * sin beta + (X1 - X0) * cos beta
                - (- (Y2 - Y0) * sin beta + (X2 - X0) * cos beta)))
    with (((Y1 - Y2) * (Y1 - Y2) + (X1 - X2) * (X1 - X2))
          * (sin beta * sin beta + cos beta * cos beta)) by ring.
  rewrite H. ring.
Qed.

(* -------------------------------------------------------------------------- *)
(* §2  Clothoid transition end conditions (Koc §2).                           *)
(*                                                                            *)
(* The clothoid TC1 has linear curvature k(l) = l/(R L) over l in [0,L].      *)
(* Its tangent angle is the integral theta(l) = l^2/(2 R L); the paper's      *)
(* pivotal observation is that the END angle theta(L) = L/(2R) is             *)
(* TYPE-INDEPENDENT -- every standard transition family shares it -- so the   *)
(* downstream tangency bookkeeping (eq (7): s_K1 = tan(theta(L) - alpha/2))   *)
(* never depends on which family the designer picked.                        *)
(* -------------------------------------------------------------------------- *)

Definition koc_clothoid_curvature (Rr L l : R) : R := l / (Rr * L).

Definition koc_clothoid_angle (Rr L l : R) : R := / (2 * Rr * L) * (l * l).

(* theta really is the antiderivative of k: at every l the derivative of the
   angle function is the curvature.  (This is the "theta = integral of k"
   step the paper takes silently.) *)
Theorem koc_clothoid_angle_deriv :
  forall Rr L l,
    Rr <> 0 -> L <> 0 ->
    derivable_pt_lim (koc_clothoid_angle Rr L) l
                     (koc_clothoid_curvature Rr L l).
Proof.
  intros Rr L l HR HL.
  unfold koc_clothoid_angle, koc_clothoid_curvature.
  assert (Hsq : derivable_pt_lim (fun x => x * x) l (l + l)).
  { pose proof (derivable_pt_lim_mult id id l 1 1
                  (derivable_pt_lim_id l) (derivable_pt_lim_id l)) as H.
    unfold id in H.
    replace (l + l) with (1 * l + l * 1) by ring. exact H. }
  pose proof (derivable_pt_lim_scal (fun x => x * x) (/ (2 * Rr * L)) l
                (l + l) Hsq) as H.
  replace (l / (Rr * L)) with (/ (2 * Rr * L) * (l + l)) by (field; lra).
  exact H.
Qed.

(* Start conditions: zero curvature and zero angle at the straight. *)
Lemma koc_clothoid_start :
  forall Rr L,
    Rr <> 0 -> L <> 0 ->
    koc_clothoid_curvature Rr L 0 = 0 /\ koc_clothoid_angle Rr L 0 = 0.
Proof.
  intros. unfold koc_clothoid_curvature, koc_clothoid_angle.
  split; field; lra.
Qed.

(* End curvature: exactly the arc's 1/R -- the C0 curvature join to CA1. *)
Lemma koc_clothoid_end_curvature :
  forall Rr L,
    Rr <> 0 -> L <> 0 ->
    koc_clothoid_curvature Rr L L = / Rr.
Proof.
  intros. unfold koc_clothoid_curvature. field; lra.
Qed.

(* End angle: theta(L) = L / (2 R) -- the paper's type-independent constant
   that all downstream tangency formulas (eqs (7), (22), (30)) consume. *)
Theorem koc_clothoid_end_angle :
  forall Rr L,
    Rr <> 0 -> L <> 0 ->
    koc_clothoid_angle Rr L L = L / (2 * Rr).
Proof.
  intros. unfold koc_clothoid_angle. field; lra.
Qed.

(* -------------------------------------------------------------------------- *)
(* §3  Arc centre from the tangency point (Koc eqs (8),(9) and (23),(24)).    *)
(*                                                                            *)
(* At the transition end K the tangent has slope s.  The arc centre S must    *)
(* lie on the normal at K, at distance R.  The paper divides by sqrt(1+s^2);  *)
(* we carry the normaliser as a hypothesis u > 0, u^2 = 1 + s^2, so the       *)
(* whole statement is rational in the inputs and closes by field/nra.        *)
(* A sign error here is the classic alignment bug: the centre lands on the    *)
(* wrong side of the track and the "arc" meets the transition in a kink.      *)
(*                                                                            *)
(* SIGN CONVENTION: the normal offset direction is (s, -1)/u -- the centre    *)
(* BELOW the curve (Koc's Figs 2-3: system convex upward, positive            *)
(* curvature).  The mirrored convention (-s, 1)/u (centre above) appears in   *)
(* §4 as the point-from-centre direction, and both are exercised by the       *)
(* 3-4-5 examples.  This is intentional -- do NOT "fix" the sign; flipping    *)
(* it here silently moves every centre to the wrong side of the track.        *)
(* -------------------------------------------------------------------------- *)

Theorem koc_center_on_normal :
  forall xK yK s Rr u,
    0 < u -> u * u = 1 + s * s ->
    let S := mkPoint (xK + s * Rr / u) (yK - Rr / u) in
    let K := mkPoint xK yK in
    (* distance: |SK|^2 = R^2 *)
    dist_sq S K = Rr * Rr /\
    (* perpendicularity: (S-K) . (1,s) = 0, i.e. SK is the normal at K *)
    (px S - px K) * 1 + (py S - py K) * s = 0.
Proof.
  intros xK yK s Rr u Hu Husq S K.
  assert (Hne : u <> 0) by lra.
  unfold S, K, dist_sq; simpl.
  split.
  - transitivity (Rr * Rr * (1 + s * s) / (u * u)).
    + field. exact Hne.
    + rewrite <- Husq. field. exact Hne.
  - field. exact Hne.
Qed.

(* -------------------------------------------------------------------------- *)
(* §4  The prescribed-slope point of a circle (Koc eqs (31),(32)).            *)
(*                                                                            *)
(* Conversely: given the centre S and a target tangent slope s (dictated by   *)
(* where transition TC3 must take over), the point K on the circle whose      *)
(* tangent has slope s sits at S + (R/u) * (-s, 1).  This is how the paper    *)
(* locates the END of arc CA2 -- the handover point to the last transition.   *)
(* -------------------------------------------------------------------------- *)

Theorem koc_slope_point_on_circle :
  forall xS yS s Rr u,
    0 < u -> u * u = 1 + s * s ->
    let K := mkPoint (xS - s * Rr / u) (yS + Rr / u) in
    let S := mkPoint xS yS in
    (* K is on the circle of radius R about S *)
    dist_sq K S = Rr * Rr /\
    (* the radius SK is perpendicular to the slope-s direction, so the
       tangent to the circle at K has exactly slope s *)
    (px K - px S) * 1 + (py K - py S) * s = 0.
Proof.
  intros xS yS s Rr u Hu Husq K S.
  assert (Hne : u <> 0) by lra.
  unfold K, S, dist_sq; simpl.
  split.
  - transitivity (Rr * Rr * (1 + s * s) / (u * u)).
    + field. exact Hne.
    + rewrite <- Husq. field. exact Hne.
  - field. exact Hne.
Qed.

(* -------------------------------------------------------------------------- *)
(* §5  Setting out along a tangent (Koc eqs (11),(12),(14),(15)).             *)
(*                                                                            *)
(* Moving distance d from K along the direction of slope s lands at           *)
(* M = K + (d/u)(1, s).  With d = R tan(alpha/2) this is the surveyor's       *)
(* tangent-length step: M is the intersection of the two tangents of an arc   *)
(* with turning angle alpha (the point the paper calls M1), the stake every   *)
(* setting-out crew places first.                                             *)
(* -------------------------------------------------------------------------- *)

Theorem koc_tangent_setout :
  forall xK yK s d u,
    0 < u -> u * u = 1 + s * s ->
    let M := mkPoint (xK + d / u) (yK + s * d / u) in
    let K := mkPoint xK yK in
    (* M lies on the slope-s line through K *)
    (py M - py K) = s * (px M - px K) /\
    (* at squared distance exactly d^2 *)
    dist_sq M K = d * d.
Proof.
  intros xK yK s d u Hu Husq M K.
  assert (Hne : u <> 0) by lra.
  unfold M, K, dist_sq; simpl.
  split.
  - field. exact Hne.
  - transitivity (d * d * (1 + s * s) / (u * u)).
    + field. exact Hne.
    + rewrite <- Husq. field. exact Hne.
Qed.

(* The tangent-length instance: d = R tan(alpha/2) gives |KM|^2 =
   R^2 tan^2(alpha/2) -- Koc's |K1 M1| = R1 tan(alpha1/2). *)
Corollary koc_tangent_length :
  forall xK yK s Rr alpha u,
    0 < u -> u * u = 1 + s * s ->
    dist_sq (mkPoint (xK + Rr * tan (alpha / 2) / u)
                     (yK + s * (Rr * tan (alpha / 2)) / u))
            (mkPoint xK yK)
    = (Rr * tan (alpha / 2)) * (Rr * tan (alpha / 2)).
Proof.
  intros xK yK s Rr alpha u Hu Husq.
  pose proof (koc_tangent_setout xK yK s (Rr * tan (alpha / 2)) u Hu Husq)
    as [_ Hd].
  exact Hd.
Qed.

(* -------------------------------------------------------------------------- *)
(* §6  Worked example: the exact 3-4-5 instance.                              *)
(*                                                                            *)
(* Slope s = 3/4 gives 1 + s^2 = 25/16 = (5/4)^2, so u = 5/4 and every        *)
(* quantity is rational: from tangency point K = (0,0) with R = 5 the centre  *)
(* is S = (3,-4) (a 3-4-5 triangle), and setting out d = 2 along the tangent  *)
(* lands at M = (8/5, 6/5).  A concrete, sqrt-free witness that §3-§5 are     *)
(* non-vacuous, in the style of the corpus's oracle galleries.                *)
(* -------------------------------------------------------------------------- *)

Example koc_example_345_center :
  dist_sq (mkPoint 3 (-4)) (mkPoint 0 0) = 5 * 5 /\
  (3 - 0) * 1 + ((-4) - 0) * (3 / 4) = 0.
Proof.
  unfold dist_sq; simpl. split; lra.
Qed.

Example koc_example_345_center_is_koc :
  mkPoint (0 + (3/4) * 5 / (5/4)) (0 - 5 / (5/4)) = mkPoint 3 (-4).
Proof.
  f_equal; lra.
Qed.

Example koc_example_345_setout :
  let M := mkPoint (0 + 2 / (5/4)) (0 + (3/4) * 2 / (5/4)) in
  (py M - 0) = (3/4) * (px M - 0) /\ dist_sq M (mkPoint 0 0) = 2 * 2.
Proof.
  cbv zeta. unfold dist_sq; simpl. split; lra.
Qed.

(* -------------------------------------------------------------------------- *)
(* §7  Audit footprint.                                                       *)
(* -------------------------------------------------------------------------- *)

Print Assumptions koc_roundtrip_global_local.
Print Assumptions koc_to_local_isometry.
Print Assumptions koc_clothoid_angle_deriv.
Print Assumptions koc_clothoid_end_angle.
Print Assumptions koc_center_on_normal.
Print Assumptions koc_slope_point_on_circle.
Print Assumptions koc_tangent_length.
