<!-- SPDX-FileCopyrightText: 2026 Merkator Group -->
<!-- SPDX-License-Identifier: LicenseRef-Merkator-Proprietary-NoAITraining -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Clothoid.Halley.Bench</RootNamespace>
    <TieredCompilation>true</TieredCompilation>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clothoid.Halley\Clothoid.Halley.csproj" />
  </ItemGroup>

</Project>
